### ISSUE TITLE
Add support of cellArea/exactEdgeLength/pointDist to h3-reactnative module

### ISSUE THREAD

**Issue by valeriik** [uber/h3-js#106]
There are no **cellArea, exactEdgeLength, pointDist** functions in [h3-reactnative](https://github.com/realPrimoh/h3-reactnative)

**Comment by nrabinowitz** [comment]
Seems like this issue should be filed in that repo, then? That's a fork, we don't maintain it.

**Comment by valeriik** [comment]
Yes, but there written:
"Post bug reports or feature requests to the [Github Issues page](https://github.com/uber/h3-js/issues)" :)
So, all who using "h3-reactnative" do not know where posts feature requests/issues :)

**Comment by nrabinowitz** [comment]
As I understand it, `h3-reactnative` is a very light fork of `h3-js` to work around a couple of environment issues with the main library's build. In this case, the issue isn't a bug with the main library, it's that the fork hasn't been updated, so that should be posted to their repository. Please repost there.

Ideally `h3-js` would work fine with React Native, I just haven't had the time or the familiarity with the RN framework to make this happen yet.
