### ISSUE TITLE
Cannot use 'in' operator to search for 'toJSON'

### ISSUE THREAD

**Issue by botzill** [uber/h3-js#125]
I try to use `polyfill` on a country like `CAN` or `RUS`, but I get errros like:

```
Cannot use 'in' operator to search for 'toJSON' in abort(Assertion failed: adjacentFaceDir[tmpFijk.face][fijk.face] == KI, at: faceijk.c,581,_faceIjkPentToGeoBoundary). Build with -s ASSERTIONS=1 for more info.
```
 
```
Cannot use 'in' operator to search for 'toJSON' in abort(OOM). Build with -s ASSERTIONS=1 for more info.
```

Any idea on how to fix this?

**Comment by nrabinowitz** [comment]
I'm not sure about the `Cannot use 'in' operator to search for 'toJSON'` part (this is likely specific to your application, I haven't seen it before). The failed assertions may indicate problems with input.

- The `abort(OOM)` message is fairly straightforward, you've run out of memory. We build H3 for use in JS with Emscripten, setting `TOTAL_MEMORY=33554432` and `ALLOW_MEMORY_GROWTH=1`, so this is likely an actual OOM for your system resources, as Emscripten should request more memory if possible. This is likely because either your input polygon is too detailed (i.e. too many vertices) or your requested H3 resolution is too fine, resulting in too many indexes.

- I haven't seen assertion errors on the `adjacentFaceDir` line - do you have sample input that throws this error?
