### ISSUE TITLE
Hexagons Resolution

### ISSUE THREAD

**Issue by mateuscardoso99** [uber/h3-js#188]
Hello!

I would like to know if there is a way to use a resolution between 3 and 4 for the hexagons, because in resolution 3 they are very large, and in resolution 4 the hexagons are very small, I would like the hexagons to be larger than resolution 4 but smaller than resolution 3.

resolution 3:
![2](https://github.com/uber/h3-js/assets/50881853/19ca1817-45ef-45e4-8119-8a04006ada77)

resolution 4:
![1](https://github.com/uber/h3-js/assets/50881853/8178993c-05a3-4c21-b080-24782cf8bd6f)

thanks!

**Comment by nrabinowitz** [comment]
Unfortunately no - H3 has 16 resolutions, and they are all fixed in size, with each subsequent resolution using cells that are approximately 1/7th the size of the parent resolution. Because of the fixed relationship between parent cells and child cells, there's no way to support custom or partial resolutions.
