### ISSUE TITLE
Polyfill glitching out over large areas bug?

### ISSUE THREAD

**Issue by james-berry** [uber/h3-js#24]
Hi all, 

I am attempting to use h3 to generate a GeoJSON polygon that I will then overlay on a mapbox map. When I try and polyfill(blue) a large square polygon(red) the resulting output gets really glitchy (see screenshots)

![screen shot 2018-10-22 at 17 27 32](https://user-images.githubusercontent.com/40232287/47304981-0cfced00-d620-11e8-99c9-d6628f46d18a.png)

However when I halve the size of the red box, the polyfill works as intended? 

![screen shot 2018-10-22 at 17 28 13](https://user-images.githubusercontent.com/40232287/47304984-0d958380-d620-11e8-8624-ba4c70b7ea4f.png)

```
const polygon = [
        [minLon, maxLat],
        [maxLon, maxLat],
        [maxLon, minLat],
        [minLon, minLat]
    ];
    const hexagons = h3.polyfill(polygon, 1, true);
    
    let hexFeatures = []
    for(let h of hexagons){
        let hexFeature = {
            'type': 'Feature',
            'geometry': {
                'type': 'Polygon',
                'coordinates': [h3.h3ToGeoBoundary(h, true)]
            }
        }
        hexFeatures.push(hexFeature)
    }

let hexGroup = {
        "id": "hex",
        "type": "fill",
        "source": {
            "type": "geojson",
            "data": {
                "type": "FeatureCollection",
                "features": hexFeatures
            }
        },
        'layout': {},
        'paint': {
            'fill-color': '#0000ff',
            'fill-opacity': 0.50
        }
    }


    map.addLayer(worldGroup)
```

Is this a possible bug?

Thanks

**Comment by nrabinowitz** [comment]
There are two issues here, both (unfortunately) expected and somewhat documented:

* The current H3 polyfill algorithm can't deal with polygon segments of greater than 180 degrees longitude. Otherwise, we interpret the bounding box of the polygon as crossing the antimeridian. The alternative was to require incoming polygons to follow the [Right Hand Rule](https://gis.stackexchange.com/questions/259944/polygons-and-multipolygons-should-follow-the-right-hand-rule), and while we obey this in output we didn't want to enforce it in input. So what you're seeing in the first image is the set of hexagons in the bounding box between the western edge of your real bounding box (interpreted as east) and the eastern edge of your bounding box (interpreted as west).

* Mapbox doesn't deal well with drawing polygons that cross the antimeridian. So the cross-globe lines you see in the first image are a rendering artifact, not actual H3 output. The fix is to adjust the geometry to go outside the +-180 degree longitude range (i.e. a segment from longitude -179 to longitude 179 would need to be rewritten as going from -179 to -181).

So unfortunately this is "working as expected". You can polyfill the area by using multiple bounding boxes, and you can draw it correctly by adjusting the output geometry to what Mapbox expects.

**Comment by visagegod** [comment]
Many thanks for a fast, clear & consise reply! Can probably close this issue.
