### ISSUE TITLE
h3.h3Distance is returning kRings number rather than the actual distance in Km

### ISSUE THREAD

**Issue by Msarnaot** [uber/h3-js#49]
As per the following example https://github.com/uber/h3/blob/master/examples/distance.c
When running:
h3.h3Distance('842764bffffffff', '840ee05ffffffff');
I get 18, which is the number of kRings and not distance in km. Or is this intended behavior of this function?

**Comment by isaacbrodsky** [comment]
Yes, that is expected behavior. `h3Distance` returns grid distance between two cells. In that example, `h3Distance` corresponds to the line that reads "grid distance".

To get the distance in kilometers, you would need to take the center of the two cells and then use something like the Haversine distance formula, which is the function `haversineDistance` at the top of that example.

**Comment by Msarnaot** [comment]
Thanks for the clarification Isaac
