### ISSUE TITLE
Fusion build process fails to import h3-js correctly

### ISSUE THREAD

**Issue by maxijb** [uber/h3-js#51]
https://github.com/uber/h3-js/blob/0ef85b252c145ca70b23427a3aa62966931c2641/package.json#L24

The `fusionJS` build process is misled by this line and will try to import `dist/h3-js.es.js` instead of `dist/h3-js.js`. 

After that happens, webpack/babel transpile the module in a way that other modules will try to find the functions under `h3Js.default.geoToH3`, instead of the correct `h3Js.geoToH3`.

Changing this line locally to `"module": "dist/h3-js.js"` fixes my issue, but I'm wondering if that will break other projects instead.

If you need to know, I'm using the package `@uber/h3-overlays`, which imports `@uber/h3-transitional`, which in turn imports `h3-js`.

I would appreciate if you could take a look and shed some light whether we can change the `module` file or not.

**Comment by nrabinowitz** [comment]
Investigation in the consuming packages suggests that the problem here is using `import h3 from ''h3-js` instead of `import * as h3 from 'h3-js'` - it appears that we're doing the correct thing, though we may have introduced a bug for consumers using the former syntax when we updated to ES6 exports.
