### ISSUE TITLE
Hexagons with > 6 sides

### ISSUE THREAD

**Issue by anthonynorth** [uber/h3-js#53]
`h3ToGeoboundary` can rarely create hexagons with > 6 sides. 

Two examples of this behavior from different base cells: `85a60003fffffff`, `859c7003fffffff`.
See examples [examples](https://gist.github.com/anthonynorth/326235470e6b6b6d266dd611738b6377)

**Comment by isaacbrodsky** [comment]
Hi, I believe this is expected behavior. H3 introduces some "distortion" vertices to cells that lay on the edge of the icosahedron. (see also uber/h3#208, uber/h3#209) These are only present at the Class III (odd numbered) resolutions. These cells are still topologically hexagons or pentagons because they have 6 or 5 neighboring cells, but they may have a slightly unusual shape.

**Comment by nrabinowitz** [comment]
This is indeed expected - if you look in the [H3 inspector](https://observablehq.com/@nrabinowitz/h3-index-inspector) (now with icosahedron edges!) you can see exactly where the distortion occurs.

@isaac, I wonder if we should have the short "gotcha" section in the docs that addresses FAQs like this - I'm not sure it's fully covered, and it tends to be surprising for users.

**Comment by anthonynorth** [comment]
Thanks for the info.
@nrabinowitz, I hadn't seen your notebook; that would've saved be building this: [H3 Distorted Hexagons](https://observablehq.com/@anthonynorth/h3-distorted-hexagons)

**Comment by nrabinowitz** [comment]
> @nrabinowitz, I hadn't seen your notebook; that would've saved be building this: [H3 Distorted Hexagons](https://observablehq.com/@anthonynorth/h3-distorted-hexagons)

Still, that's pretty cool :).
