### ISSUE TITLE
Shape distortion while using compact

### ISSUE THREAD

**Issue by mikecolonna** [uber/h3-js#99]
While using the compact feature to optimize a cluster of hexes at high resolution, I noticed the introduction of gaps into the cluster like so:
<img width="1130" alt="Screen Shot 2020-10-16 at 2 26 08 PM" src="https://user-images.githubusercontent.com/20339513/96299901-bcc48580-0fc2-11eb-9c3f-efdb17588aef.png">

I understand that these gaps are an expected distortion as a result of choosing hexagons as the preferred tessellation shape (as outlined in the H3 eng blog [announcement](https://eng.uber.com/h3/#:~:text=H3%20supports%20sixteen%20resolutions.,contained%20within%20a%20parent%20cell)). I was looking to understand more details about this tessellation algorithm and if its possible to close these gaps. 

Perhaps, we could create a tangential compact function that slightly increases the area covered by these hexagons in order to fill these gaps? I understand this would cause more extensive overlaps, but in our use case that would be preferable to having gaps in the area.

Could you provide more details regarding this algorithm? Thanks! @nrabinowitz

**Comment by nrabinowitz** [comment]
I think there's some confusion here about the nature of `compact`. The `compact` algorithm is essentially a data compression algorithm - it represents the compacted set in a compressed form, and can be used for efficient data storage/transfer of large areas, some lookup algorithms, etc. But the cells in the compacted set do not cover the _area_ of the uncompacted set, as your image shows, because of the imperfect hierarchical containment of a hexagon-based grid system. 

Whether and how this matters depends on your use case. If you want to _see_ the exact area covered by the compacted set, you need to `uncompact` it, so `compact` is not a good optimization for display. But it can be very useful for data transfer, reducing memory consumption, and some lookup operations.

**Comment by dfellis** [comment]
There is another way to look at it :) We could consider only the Resolution 15 hexagons "true hexagons" and then Resolution 14 is collections of 7 hexagons packed together to looked approximately like the hexagon we render/present, and Resolution 13 is then 49 resolution 15 hexagons packed together, etc.

This perspective will produce perfectly contiguous compacted sets, but the boundaries of the hexagons above Resolution 15 are *not* truly hexagonal, but fractal approximations of hexagons.

This perspective is not actually supported by H3 at this time, since it's esoteric and confusing, and I can't think of any *valid* reason why you'd want it, except if you don't care about the shape of the hexagon and just want hexagon-*ish* shapes that perfectly subdivided like S2 cells perfectly subdivide. The only niche I can think of that would desire this is something that still wants k-ring style quasi-circular fast lookup, singular class of neighbors (all neighbors being equidistant from each other as measured by their centerpoints), and perfect subdivision for rapidly and accurately re-indexing between resolutions when some density threshold is reached.

But anyone needing those qualities can simply index always at res 15 and then simply truncate the lower bits to the desired resolution.

With respect to the visualization above, though, I would recommend uncompacting the set before displaying it, or mapping each hexagon via h3ToChildren to the minimum size and then h3SetToMultiPolygon to get GeoJSON in the fractally-hexagonal shapes mentioned above and then rendering those if keeping the "compactness" of the data present in the visualization is desired.

**Comment by mikecolonna** [comment]
Thanks @nrabinowitz @dfellis! Your insights have been very helpful. For our use case, we're going to move forward with using an uncompacted set of hexagons at resolution 10 for now, so as to minimize eng lift and ensure the entire area is covered. If this turns out not to be sufficient, we'll investigate higher resolutions and use `compact` as a way to compress these hexes across our pipelines.
